# Generated by Django 5.2.3 on 2026-09-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image_alter_product_price_wishlist'),
        ('product', '0002_remove_product_image_remove_product_name_and_more'),
    ]

    operations = [
    ]
